apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "tornado-app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "tornado-app.selectorLabels" . | nindent 6 }}
  ingress:
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: {{ .Values.environment.PORT | int }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: redis
    ports:
    - protocol: TCP
      port: 6379
  - to: 
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
