name: Build Docker Image

on:
  workflow_call:
    outputs:
      version:
        value: ${{ jobs.build.outputs.version }}
    secrets:
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-tags.outputs.version }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Set image tags
      id: set-tags
      run: |
        TAGS="mohammedx3/tornado-app:${{ github.sha }}"
        
        if [[ $GITHUB_REF == refs/heads/master ]]; then
          TAGS="$TAGS,mohammedx3/tornado-app:dev"
        fi
        
        if [[ $GITHUB_REF == refs/tags/v* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
          TAGS="$TAGS,mohammedx3/tornado-app:$VERSION,mohammedx3/tornado-app:prod,mohammedx3/tornado-app:latest"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        fi
        
        echo "tags=$TAGS" >> $GITHUB_OUTPUT

    - name: Build and scan Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./deploy/images/Dockerfile
        push: false
        load: true
        tags: mohammedx3/tornado-app:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Scan image for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'mohammedx3/tornado-app:${{ github.sha }}'
        format: 'table'
        output: 'trivy-results.txt'
        severity: 'CRITICAL,HIGH'
        exit-code: '0'

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: mohammedx3
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./deploy/images/Dockerfile
        push: true
        tags: ${{ steps.set-tags.outputs.tags }}
        cache-from: type=gha

    - name: Upload scan results
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report
        path: trivy-results.txt
        if-no-files-found: warn
