name: Tornado App CI/CD

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  
  build:
    needs: [tests]
    if: success() && github.event_name == 'push'
    uses: ./.github/workflows/build.yml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  
  deploy-dev:
    needs: build
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
    uses: ./.github/workflows/deploy.yml
    with:
      image_tag: ${{ github.sha }}
      env_file: values-dev.yaml
      environment: development
  
  deploy-prod:
    needs: [build]
    if: success() && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/deploy.yml
    with:
      image_tag: ${{ needs.build.outputs.version || github.ref_name }}
      env_file: values-prod.yaml
      environment: production
